function render(){let v=todayView();if(tab==='life')v=lifeView();if(tab==='notes')v=notesView();if(tab==='people')v=peopleView();if(tab==='insights')v=insightsView();if(tab==='adventures')v=adventuresView();if(tab==='connectors')v=connectorsView();if(tab==='settings')v=settingsView();$('#app').innerHTML=shell(v);bindCommon();if(tab==='today')bindToday();if(tab==='notes')bindNotes();if(tab==='people')bindPeople();if(tab==='adventures')bindAdv();if(tab==='connectors')bindConnectors();if(tab==='settings')bindSettings()}
function bindCommon(){$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})}
function shift(n){const d=new Date(selected+'T12:00:00');d.setDate(d.getDate()+n);selected=d.toISOString().slice(0,10);render()}
function bindToday(){$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);$('#date').onchange=e=>{selected=e.target.value;render()};$$('[data-metric]').forEach(i=>i.onchange=e=>{const x=E();x.metrics[e.target.dataset.metric]=e.target.value===''?null:Number(e.target.value);put(x)});$$('[data-habit]').forEach(b=>b.onclick=()=>{const x=E(),k=b.dataset.habit;x.habits[k]=!x.habits[k];put(x)});$$('[data-act]').forEach(b=>b.onclick=()=>{const x=E(),k=b.dataset.act;x.activities[k]=x.activities[k]?0:1;x.habits.movement=Object.values(x.activities).some(Boolean);put(x)});$('#german').onchange=e=>{const x=E();x.germanMinutes=Number(e.target.value)||0;x.habits.german=x.germanMinutes>0;put(x)};$('#guitar').onchange=e=>{const x=E();x.guitarMinutes=Number(e.target.value)||0;x.habits.guitar=x.guitarMinutes>0;put(x)};$('#invite').onclick=()=>{const x=E();x.invitation=!x.invitation;put(x)};['best','hardest','sentence'].forEach(k=>$('#'+k).onchange=e=>{const x=E();x.journal[k]=e.target.value;put(x)})}
function bindNotes(){$('#saveNote').onclick=()=>{const title=$('#noteTitle').value.trim(),body=$('#noteBody').value.trim();if(!title&&!body)return;state.notes.unshift({id:uid(),title:title||'Untitled',body,tags:$('#noteTags').value.split(',').map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});save();render()};$$('[data-del-note]').forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(n=>n.id!==b.dataset.delNote);save();render()})}
function bindPeople(){$('#savePerson').onclick=()=>{const name=$('#personName').value.trim();if(!name)return;state.people.unshift({id:uid(),name,metAt:$('#personMet').value.trim(),notes:$('#personNotes').value.trim(),interactions:1,firstMet:today(),lastSeen:today(),messageable:false,outsideHangout:false,friend:false});save();render()};$$('[data-person]').forEach(b=>b.onclick=()=>{const p=state.people.find(x=>x.id===b.dataset.id);if(!p)return;const a=b.dataset.person;if(a==='seen'){p.interactions=(p.interactions||0)+1;p.lastSeen=today()}else if(a==='messageable')p.messageable=!p.messageable;else if(a==='hangout')p.outsideHangout=!p.outsideHangout;else if(a==='friend')p.friend=!p.friend;save();render()})}
function bindAdv(){$('#saveAdv').onclick=()=>{const title=$('#advTitle').value.trim();if(!title)return;state.adventures.unshift({id:uid(),title,date:$('#advDate').value,place:$('#advPlace').value.trim(),people:$('#advPeople').value.trim(),notes:$('#advNotes').value.trim()});save();render()}}
function download(name,text,type){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
function expJson(){download('life100-'+today()+'.json',JSON.stringify(state,null,2),'application/json')}
function expCsv(){const h=['date','weight','vo2','sleep','steps','mood','energy','anxiety','german_minutes','guitar_minutes','invitation','activities','best','hardest','sentence'];const rows=Object.values(state.entries).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>[e.date,e.metrics?.weight??'',e.metrics?.vo2??'',e.metrics?.sleep??'',e.metrics?.steps??'',e.metrics?.mood??'',e.metrics?.energy??'',e.metrics?.anxiety??'',e.germanMinutes||0,e.guitarMinutes||0,e.invitation?1:0,Object.keys(e.activities||{}).filter(k=>e.activities[k]).join('|'),e.journal?.best||'',e.journal?.hardest||'',e.journal?.sentence||'']);download('life100-'+today()+'.csv',[h,...rows].map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function expMd(){const lines=['# Life 100','',state.startDate+' → '+state.endDate,'','## Scoreboard',...state.goals.map(g=>'- '+g.label+': '+goalValue(g.id)+'/'+g.target+' '+g.unit),'','## People',...state.people.map(p=>'- **'+p.name+'** · '+(p.metAt||'—')+' · '+(p.interactions||1)+' interactions'),'','## Notes',...state.notes.flatMap(n=>['### '+n.title,n.body,''])];download('life100-'+today()+'.md',lines.join('\n'),'text/markdown')}
function expIcs(){const ev=[['SVN Basketball','20261006T200000','20261006T220000'],['Bouldering community','20261011T110000','20261011T130000'],['Weekly review','20261011T190000','20261011T192000']];const body=ev.map(([s,a,b],i)=>['BEGIN:VEVENT','UID:life100-'+i+'@local','DTSTART;TZID=Europe/Berlin:'+a,'DTEND;TZID=Europe/Berlin:'+b,'RRULE:FREQ=WEEKLY;UNTIL=20270112T235959Z','SUMMARY:'+s,'END:VEVENT'].join('\r\n')).join('\r\n');download('life100-calendar.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Life100//EN',body,'END:VCALENDAR'].join('\r\n'),'text/calendar')}
async function sb(){if(!state.settings.supabaseUrl||!state.settings.supabaseAnonKey)throw Error('Save Supabase URL and anon key first.');const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');return createClient(state.settings.supabaseUrl,state.settings.supabaseAnonKey,{auth:{persistSession:true,detectSessionInUrl:true}})}
async function signin(){const c=await sb();const {error}=await c.auth.signInWithOtp({email:state.settings.syncEmail,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;alert('Magic link sent. Open it on this device.')}
async function pushCloud(){const c=await sb(),{data:{session}}=await c.auth.getSession();if(!session)throw Error('Sign in first.');const {error}=await c.from('life100_snapshots').upsert({user_id:session.user.id,payload:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;alert('Cloud snapshot pushed.')}
async function pullCloud(){const c=await sb(),{data:{session}}=await c.auth.getSession();if(!session)throw Error('Sign in first.');const {data,error}=await c.from('life100_snapshots').select('payload').eq('user_id',session.user.id).single();if(error)throw error;state=merge(fresh(),data.payload);save();render();alert('Cloud snapshot restored.')}
function safe(fn){return async()=>{try{await fn()}catch(e){alert(e.message||String(e))}}}
function bindConnectors(){$('#saveSb').onclick=()=>{state.settings.supabaseUrl=$('#sbUrl').value.trim();state.settings.supabaseAnonKey=$('#sbKey').value.trim();state.settings.syncEmail=$('#sbEmail').value.trim();save();alert('Saved locally.')};$('#signIn').onclick=safe(signin);$('#push').onclick=safe(pushCloud);$('#pull').onclick=safe(pullCloud);$('#json').onclick=expJson;$('#csv').onclick=expCsv;$('#md').onclick=expMd;$('#ics').onclick=expIcs;$('#import').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=merge(fresh(),JSON.parse(r.result));save();render()}catch{alert('Invalid backup')}};r.readAsText(f)};const base=location.origin+location.pathname.replace(/index\.html$/,'');$('#copyShortcut').onclick=()=>navigator.clipboard.writeText(base+'?action=metric&key=weight&value=85.4');$('#copyPrompt').onclick=()=>navigator.clipboard.writeText('Review my Life 100 tracking data. Identify what is improving, what is slipping, correlations between social contact, exercise, sleep and mood, and give me exactly 3 adjustments for next week. Do not create a giant optimization plan.')}
function bindSettings(){const commit=()=>{state.settings.displayName=$('#setName').value;state.startDate=$('#setStart').value;state.endDate=$('#setEnd').value;state.settings.weightTargetLow=Number($('#setWL').value);state.settings.weightTargetHigh=Number($('#setWH').value);state.settings.vo2Target=Number($('#setV').value);save();render()};$$('.settingsGrid input').forEach(x=>x.onchange=commit);$('#reset').onclick=()=>{if(confirm('Reset all local Life100 data?')){localStorage.removeItem(KEY);state=fresh();selected=today();render()}}}
